### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by ryanrca** [gustavobissolli/vue2-select2#1]
.... but how do you use it?
Could you append some examples to your readme?

Thanks!

**Comment by xiaolongnk** [comment]
can this work?

**Comment by bissolli** [comment]
Sorry Guys!

Not yet! I am going to make it works for the weekend then I'll let you know!

**Comment by jasonlfunk** [comment]
https://gist.github.com/jasonlfunk/a7befde14541e6e9c959f5e383e9e31f

Here is a start if you want my take on it. I only needed `multiple` support so I didn't make it do both single and multiple. However, it should be easy to update.
